import { Link } from 'react-router-dom';

const GDPRPage = () => {
  const lastUpdated = 'October 26, 2025';

  return (
    <div className="space-y-6">
      <div className="text-center md:text-left">
        <p className="text-xs uppercase tracking-[0.4em] text-white/50">Privacy & Data</p>
        <h1 className="font-display text-3xl uppercase tracking-[0.25em] text-snow md:text-4xl">Privacy Policy</h1>
        <p className="mt-2 text-sm text-white/60">Last updated on {lastUpdated}.</p>
      </div>

      <section className="rounded-[1.5rem] border border-white/10 bg-carbon/90 p-6 space-y-4">
        <h2 className="text-lg font-semibold">Introduction</h2>
        <p className="text-sm text-white/60">
          This Privacy Policy describes our policies and procedures on the collection, use and disclosure of Your
          information when You use the Service and tells You about Your privacy rights and how the law protects You.
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
          collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2 className="text-lg font-semibold">Interpretation and Definitions</h2>
        <h3 className="text-sm font-semibold">Interpretation</h3>
        <p className="text-sm text-white/60">
          The words of which the initial letter is capitalized have meanings defined under the following conditions.
          The following definitions shall have the same meaning regardless of whether they appear in singular or in
          plural.
        </p>

        <h3 className="text-sm font-semibold">Definitions</h3>
        <p className="text-sm text-white/60">For the purposes of this Privacy Policy:</p>
        <ul className="ml-4 list-disc text-sm text-white/60">
          <li>
            <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
          </li>
          <li>
            <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our") refers to jinx
            esport.
          </li>
          <li>
            <strong>Country</strong> refers to Sweden.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on Your device by a website, containing details of
            Your browsing history on that website among other uses.
          </li>
          <li>
            <strong>Data Controller</strong> for the purposes of the GDPR, refers to the Company as the legal person which
            alone or jointly with others determines the purposes and means of the processing of Personal Data.
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a
            digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the
            Company.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
            Service or from the Service infrastructure itself.
          </li>
          <li>
            <strong>Website</strong> refers to jinxesport.se, accessible from https://jinxesport.se
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the Service.
          </li>
        </ul>

        <h2 className="text-lg font-semibold">Collecting and Using Your Personal Data</h2>
        <h3 className="text-sm font-semibold">Types of Data Collected</h3>
        <h4 className="text-sm font-semibold">Personal Data</h4>
        <p className="text-sm text-white/60">While using Our Service, We may ask You to provide Us with certain personally
        identifiable information that can be used to contact or identify You. This may include:</p>
        <ul className="ml-4 list-disc text-sm text-white/60">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Personal number (where provided)</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-sm font-semibold">Usage Data</h4>
        <p className="text-sm text-white/60">Usage Data is collected automatically when using the Service. It may include
        IP address, browser type and version, pages visited, time and date of visit, time spent on those pages, unique
        device identifiers and other diagnostic data.</p>

        <h3 className="text-sm font-semibold">Tracking Technologies and Cookies</h3>
        <p className="text-sm text-white/60">We use Cookies and similar tracking technologies to track the activity on
        Our Service and store certain information. Tracking technologies used may include cookies, web beacons, tags
        and scripts. You can instruct your browser to refuse all Cookies, but that may prevent parts of the Service
        from working correctly.</p>

        <h2 className="text-lg font-semibold">Use of Your Personal Data</h2>
        <p className="text-sm text-white/60">We may use Personal Data for the following purposes: to provide and
        maintain our Service, to manage Your Account, to contact You, to provide news and offers (unless you opt-out),
        to manage requests, and for business transfers or other legitimate business purposes such as analytics and
        improving the Service.</p>

        <h2 className="text-lg font-semibold">Disclosure of Your Personal Data</h2>
        <p className="text-sm text-white/60">We may share Your Personal Data with Service Providers, affiliates, business
        partners, or in connection with business transactions. We will disclose information when required to comply
        with legal obligations or to protect the rights and safety of our users.</p>

        <h2 className="text-lg font-semibold">Retention of Your Personal Data</h2>
        <p className="text-sm text-white/60">The Company will retain Your Personal Data only for as long as is necessary
        for the purposes set out in this Privacy Policy, and to comply with legal obligations.</p>

        <h2 className="text-lg font-semibold">Transfer of Your Personal Data</h2>
        <p className="text-sm text-white/60">Your information may be processed in locations outside your country. We will
        take reasonable steps to ensure data is treated securely and in accordance with this Policy.</p>

        <h2 className="text-lg font-semibold">Security of Your Personal Data</h2>
        <p className="text-sm text-white/60">We use commercially reasonable measures to protect Your Personal Data, but no
        method of transmission or storage is 100% secure.</p>

        <h2 className="text-lg font-semibold">Legal Basis for Processing under GDPR</h2>
        <p className="text-sm text-white/60">We may process Personal Data based on Consent, performance of a contract,
        legal obligations, vital interests, public interests, or legitimate interests as applicable.</p>

        <h2 className="text-lg font-semibold">Your Rights under the GDPR</h2>
        <p className="text-sm text-white/60">If you are in the EU/EEA, you have the right to request access to, correction,
        deletion, restriction, portability, and to object to processing. To exercise these rights contact us at <a
        href="mailto:info@jinxesport.se" className="text-fuchsia">info@jinxesport.se</a>. You also have the right to
        lodge a complaint with a supervisory authority.</p>

        <h2 className="text-lg font-semibold">Children's Privacy</h2>
        <p className="text-sm text-white/60">Our Service does not address anyone under the age of 13 and we do not
        knowingly collect Personal Data from children under 13. If we learn we have collected such data, we will take
        steps to delete it.</p>

        <h2 className="text-lg font-semibold">Links to Other Websites</h2>
        <p className="text-sm text-white/60">Our Service may include links to third-party sites. We are not
        responsible for their privacy practices and recommend you read their privacy policies.</p>

        <h2 className="text-lg font-semibold">Changes to this Privacy Policy</h2>
        <p className="text-sm text-white/60">We may update this Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date above.
        </p>

        <h2 className="text-lg font-semibold">Contact Us</h2>
        <p className="text-sm text-white/60">If you have any questions about this Privacy Policy, You can contact us:
        </p>
        <ul className="ml-4 list-disc text-sm text-white/60">
          <li>By visiting this page on our website: <Link to="/contact" className="text-fuchsia">Contact page</Link></li>
          <li>By sending us an email: <a href="mailto:info@jinxesport.se" className="text-fuchsia">info@jinxesport.se</a></li>
        </ul>

        <p className="mt-4 text-sm text-white/60">Back to <Link to="/" className="text-fuchsia">home</Link>.</p>
      </section>
    </div>
  );
};

export default GDPRPage;
